import type { ChartSpec } from './types';

export const CHART_SPECS: ChartSpec[] = [
  {
    id: 'summary-labour-tax',
    title: 'Labour Income Tax',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A10', valuesRange: 'B10:L10', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A11', valuesRange: 'B11:L11', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A12', valuesRange: 'B12:L12', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A13', valuesRange: 'B13:L13', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A14', valuesRange: 'B14:L14', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A15', valuesRange: 'B15:L15', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', labelCell: 'A4', valuesRange: 'B4:L4', role: 'baseline' },
    ],
  },
  {
    id: 'summary-benefit-spending',
    title: 'Benefit Spending',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A38', valuesRange: 'B38:L38', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A39', valuesRange: 'B39:L39', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A40', valuesRange: 'B40:L40', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A41', valuesRange: 'B41:L41', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A42', valuesRange: 'B42:L42', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A43', valuesRange: 'B43:L43', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', label: 'Baseline', constantValue: 0, role: 'baseline' },
    ],
  },
  {
    id: 'summary-capital-tax',
    title: 'Capital Income Tax',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A17', valuesRange: 'B17:L17', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A18', valuesRange: 'B18:L18', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A19', valuesRange: 'B19:L19', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A20', valuesRange: 'B20:L20', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A21', valuesRange: 'B21:L21', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A22', valuesRange: 'B22:L22', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', labelCell: 'A5', valuesRange: 'B5:L5', role: 'baseline' },
    ],
  },
  {
    id: 'summary-consumption-tax',
    title: 'Consumption Tax',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A24', valuesRange: 'B24:L24', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A25', valuesRange: 'B25:L25', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A26', valuesRange: 'B26:L26', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A27', valuesRange: 'B27:L27', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A28', valuesRange: 'B28:L28', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A29', valuesRange: 'B29:L29', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', labelCell: 'A6', valuesRange: 'B6:L6', role: 'baseline' },
    ],
  },
  {
    id: 'summary-total-tax-revenue',
    title: 'Total Tax Revenue',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A31', valuesRange: 'B31:L31', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A32', valuesRange: 'B32:L32', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A33', valuesRange: 'B33:L33', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A34', valuesRange: 'B34:L34', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A35', valuesRange: 'B35:L35', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A36', valuesRange: 'B36:L36', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
    ],
  },
  {
    id: 'summary-net-fiscal-impact',
    title: 'Net Fiscal Impact',
    group: 'summary',
    chartType: 'line',
    sheet: 'summary',
    xRange: 'B2:L2',
    marketPowerTag: 'all',
    series: [
      { id: 's-low-low', labelCell: 'A45', valuesRange: 'B45:L45', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A46', valuesRange: 'B46:L46', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A47', valuesRange: 'B47:L47', scenarioKey: 'high-low', role: 'scenario' },
      { id: 's-low-high', labelCell: 'A48', valuesRange: 'B48:L48', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A49', valuesRange: 'B49:L49', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A50', valuesRange: 'B50:L50', scenarioKey: 'high-high', role: 'scenario' },
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
    ],
  },
  {
    id: 'changes-over-10y',
    title: 'Changes in Total Tax Revenue and Net Fiscal Impact over 10 years',
    group: 'changes',
    chartType: 'bar',
    sheet: 'changes',
    xRange: 'A3:A8',
    marketPowerTag: 'all',
    series: [
      { id: 'total-change', labelCell: 'B2', valuesRange: 'B3:B8', role: 'scenario' },
      { id: 'net-change', labelCell: 'C2', valuesRange: 'C3:C8', role: 'scenario' },
    ],
  },
  {
    id: 'deep-labour-low',
    title: 'Labour Tax (High Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'low',
    series: [
      { id: 'baseline', labelCell: 'A4', valuesRange: 'B4:L4', role: 'baseline' },
      { id: 's-low-low', labelCell: 'A10', valuesRange: 'B10:L10', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A11', valuesRange: 'B11:L11', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A12', valuesRange: 'B12:L12', scenarioKey: 'high-low', role: 'scenario' },
    ],
  },
  {
    id: 'deep-capital-low',
    title: 'Capital Tax (High Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'low',
    series: [
      { id: 'baseline', labelCell: 'A5', valuesRange: 'B5:L5', role: 'baseline' },
      { id: 's-low-low', labelCell: 'A18', valuesRange: 'B18:L18', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A19', valuesRange: 'B19:L19', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A20', valuesRange: 'B20:L20', scenarioKey: 'high-low', role: 'scenario' },
    ],
  },
  {
    id: 'deep-capital-high',
    title: 'Capital Tax (Low Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'high',
    series: [
      { id: 'baseline', labelCell: 'A5', valuesRange: 'B5:L5', role: 'baseline' },
      { id: 's-low-high', labelCell: 'A22', valuesRange: 'B22:L22', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A23', valuesRange: 'B23:L23', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A24', valuesRange: 'B24:L24', scenarioKey: 'high-high', role: 'scenario' },
    ],
  },
  {
    id: 'deep-consumption-low',
    title: 'Consumption Tax (High Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'low',
    series: [
      { id: 'baseline', labelCell: 'A6', valuesRange: 'B6:L6', role: 'baseline' },
      { id: 's-low-low', labelCell: 'A26', valuesRange: 'B26:L26', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A27', valuesRange: 'B27:L27', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A28', valuesRange: 'B28:L28', scenarioKey: 'high-low', role: 'scenario' },
    ],
  },
  {
    id: 'deep-consumption-high',
    title: 'Consumption Tax (Low Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'high',
    series: [
      { id: 'baseline', labelCell: 'A6', valuesRange: 'B6:L6', role: 'baseline' },
      { id: 's-low-high', labelCell: 'A30', valuesRange: 'B30:L30', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A31', valuesRange: 'B31:L31', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A32', valuesRange: 'B32:L32', scenarioKey: 'high-high', role: 'scenario' },
    ],
  },
  {
    id: 'deep-total-low',
    title: 'Total Tax Revenue (High Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'low',
    series: [
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
      { id: 's-low-low', labelCell: 'A34', valuesRange: 'B34:L34', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A35', valuesRange: 'B35:L35', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A36', valuesRange: 'B36:L36', scenarioKey: 'high-low', role: 'scenario' },
    ],
  },
  {
    id: 'deep-total-high',
    title: 'Total Tax Revenue (Low Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'high',
    series: [
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
      { id: 's-low-high', labelCell: 'A38', valuesRange: 'B38:L38', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A39', valuesRange: 'B39:L39', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A40', valuesRange: 'B40:L40', scenarioKey: 'high-high', role: 'scenario' },
    ],
  },
  {
    id: 'deep-net-low',
    title: 'Net Fiscal Impact (High Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'low',
    series: [
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
      { id: 's-low-low', labelCell: 'A42', valuesRange: 'B42:L42', scenarioKey: 'low-low', role: 'scenario' },
      { id: 's-med-low', labelCell: 'A43', valuesRange: 'B43:L43', scenarioKey: 'med-low', role: 'scenario' },
      { id: 's-high-low', labelCell: 'A44', valuesRange: 'B44:L44', scenarioKey: 'high-low', role: 'scenario' },
    ],
  },
  {
    id: 'deep-net-high',
    title: 'Net Fiscal Impact (Low Domestic Value Capture)',
    group: 'deep-dive',
    chartType: 'line',
    sheet: 'charts',
    xRange: 'B2:L2',
    marketPowerTag: 'high',
    series: [
      { id: 'baseline', labelCell: 'A8', valuesRange: 'B8:L8', role: 'baseline' },
      { id: 's-low-high', labelCell: 'A46', valuesRange: 'B46:L46', scenarioKey: 'low-high', role: 'scenario' },
      { id: 's-med-high', labelCell: 'A47', valuesRange: 'B47:L47', scenarioKey: 'med-high', role: 'scenario' },
      { id: 's-high-high', labelCell: 'A48', valuesRange: 'B48:L48', scenarioKey: 'high-high', role: 'scenario' },
    ],
  },
];

